//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursak_Ol
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTestAnswer
    {
        public int Id { get; set; }
        public int UserTestId { get; set; }
        public int TestQuestionId { get; set; }
        public int UserTestQuestionAnswerId { get; set; }
        public System.DateTime AnswerDate { get; set; }
    
        public virtual UserTest UserTest { get; set; }
        public virtual TestQuestion TestQuestion { get; set; }
        public virtual TestQuestionAnswer TestQuestionAnswer { get; set; }
    }
}
